/**
 * "Python writes, JS reads" half of interop-python's bidirectional
 * conformance suite (issue #21). py_written.parquet / py_written_expected.json
 * are generated by packages/interop-python/tests/fixtures/generate_py_fixtures.py
 * (pyarrow/pandas) — read directly from that package's fixtures directory
 * rather than duplicating the file here. The inverse direction (JS writes,
 * Python reads) is verified in
 * packages/interop-python/tests/test_parquet_conformance.py against
 * js_written.parquet, generated by generate_js_fixtures.mjs using this
 * package's own writeParquet().
 */
import assert from "node:assert/strict";
import { makeTest } from "../../../test/harness.ts";
// @ts-ignore -- bun types are not installed; only evaluated under Bun (see test/harness.ts)
const { test } = makeTest((globalThis as { Bun?: unknown }).Bun ? await import("bun:test") : null);
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { readParquet } from "../src/index.ts";

const FIXTURES = fileURLToPath(new URL("../../interop-python/tests/fixtures/", import.meta.url));

test("reads a pandas/pyarrow-written Parquet file matching the expected fixture", async () => {
  const frame = await readParquet(`${FIXTURES}py_written.parquet`);
  const expected = JSON.parse(readFileSync(`${FIXTURES}py_written_expected.json`, "utf8"));

  assert.deepEqual(frame.columns, expected.columns);
  assert.deepEqual(frame.toRows(), expected.rows);
});
