/**
 * scanParquet: glob resolution + eager read+concat (see scan.ts's module doc
 * for the eager-vs-lazy decision). test/fixtures/scan/part-{0,1,2}.parquet
 * are three same-schema partitions generated by test/fixtures/generate.py.
 */
import assert from "node:assert/strict";
import { makeTest } from "../../../test/harness.ts";
// @ts-ignore -- bun types are not installed; only evaluated under Bun (see test/harness.ts)
const { test } = makeTest((globalThis as { Bun?: unknown }).Bun ? await import("bun:test") : null);
import { scanParquet } from "../src/index.ts";

const SCAN_DIR = new URL("fixtures/scan/", import.meta.url).pathname;

test("scanParquet: globs and concatenates all matching files", async () => {
  const frame = await scanParquet(`${SCAN_DIR}*.parquet`);
  assert.equal(frame.length, 30); // 3 files x 10 rows
  assert.deepEqual(frame.columns, ["id", "part", "name"]);
  const rows = frame.toRows();
  const ids = rows.map((r) => Number(r.id)).sort((a, b) => a - b);
  assert.deepEqual(
    ids,
    Array.from({ length: 30 }, (_, i) => i),
  );
});

test("scanParquet: columns/filter options are pushed down into every matched file's read", async () => {
  const frame = await scanParquet(`${SCAN_DIR}*.parquet`, { columns: ["id", "part"] });
  assert.deepEqual(frame.columns, ["id", "part"]);
  assert.equal(frame.length, 30);

  const filtered = await scanParquet(`${SCAN_DIR}*.parquet`, { filter: { part: { $eq: 1 } } });
  assert.equal(filtered.length, 10);
  assert.ok(filtered.toRows().every((r) => r.part === 1));
});

test("scanParquet: a pattern matching a single file still works", async () => {
  const frame = await scanParquet(`${SCAN_DIR}part-0.parquet`);
  assert.equal(frame.length, 10);
});

test("scanParquet: a literal (wildcard-free) path that does not exist throws the same clear error", async () => {
  // Literal paths take the stat() route (Bun 1.2's fs.glob drops absolute
  // literal paths — see globSortedParquetPaths); a miss must still be a clear error.
  await assert.rejects(() => scanParquet(`${SCAN_DIR}part-9.parquet`), /no files matched pattern/);
});

test("scanParquet: a pattern matching nothing throws a clear error", async () => {
  await assert.rejects(() => scanParquet(`${SCAN_DIR}nope-*.parquet`), /no files matched pattern/);
});
