/**
 * "Python writes, JS reads" half of interop-python's bidirectional
 * conformance suite (issue #21). py_written.arrow / py_written_expected.json
 * are generated by packages/interop-python/tests/fixtures/generate_py_fixtures.py
 * (pyarrow/pandas) — read directly from that package's fixtures directory
 * rather than duplicating the file here, so there is exactly one committed
 * copy to keep in sync. The inverse direction (JS writes, Python reads) is
 * verified in packages/interop-python/tests/test_ipc_conformance.py against
 * js_written.arrow, generated by generate_js_fixtures.mjs using this
 * package's own Frame.toIPC().
 */
import assert from "node:assert/strict";
import { makeTest } from "../../../test/harness.ts";
// @ts-ignore -- bun types are not installed; only evaluated under Bun (see test/harness.ts)
const { test } = makeTest((globalThis as { Bun?: unknown }).Bun ? await import("bun:test") : null);
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { Frame } from "../src/index.ts";

const FIXTURES = fileURLToPath(new URL("../../interop-python/tests/fixtures/", import.meta.url));

test("reads a pandas/pyarrow-written Arrow IPC file matching the expected fixture", () => {
  const bytes = readFileSync(`${FIXTURES}py_written.arrow`);
  const frame = Frame.fromIPC(new Uint8Array(bytes));
  const expected = JSON.parse(readFileSync(`${FIXTURES}py_written_expected.json`, "utf8"));

  assert.deepEqual(frame.columns, expected.columns);
  assert.deepEqual(frame.toRows(), expected.rows);
});
