/**
 * WebGPU GEMM: `out[m,n] = sum_k a[m,k] * b[k,n]` (or `b[n,k]` with
 * `transB`), row-major, f32 or f16 storage with **f32 accumulation**.
 *
 * v1 shipped a naive one-thread-per-output kernel that never beat
 * `@johnhenry/math-plus-tensor-wasm` (docs/spikes/webgpu-baseline.md). This
 * module now dispatches one of three kernels generated by gemm-kernels.ts
 * (ported from laya-js's MLX-verified WebGPU backend):
 *
 * | kernel | used when (`kernel: "auto"`) |
 * |---|---|
 * | `skinny` | `transB`, K % 4 == 0, M <= 64 |
 * | `subgroup-matrix` | device has usable subgroup matrices (see gemm-caps.ts), M > 64, K % 4 == 0, and N % 4 == 0 unless `transB` |
 * | `tiled` | everything else (any shape, any alignment) |
 *
 * Re-measured crossover vs WASM: docs/spikes/webgpu-tiled-gemm.md.
 *
 * Entry points:
 *  - {@link runGemm}: `GPUTensor` in, `GPUTensor` out — stays GPU-resident
 *    (no host round-trip), f32 or f16 (dtype follows the inputs).
 *  - {@link runGemmWGSL}: the original `Float32Array` convenience entry
 *    point (upload, dispatch, read back), same signature plus options.
 *  - {@link runGemmF16WGSL}: its f16 counterpart over binary16 bits
 *    (`Uint16Array`, tensor-core's f16 storage).
 *
 * Shader sources are specialized by (kernel, dtype, transB, operand
 * alignment, and for `skinny` the rows-per-thread bucket) — NOT by exact
 * shape: m/n/k travel in a uniform buffer, so every shape that lands in the
 * same variant reuses one compiled pipeline (gpu-runtime.ts's cache).
 *
 * Not supported (disclosed per AGENTS.md): batched/broadcast GEMM (2-D
 * only — loop over the batch yourself), strided/offset operands, mixed
 * dtypes (A, B and the output share one dtype), bias/activation epilogues,
 * and f16 on devices without `shader-f16` (throws rather than silently
 * widening).
 */
import { GPUTensor } from "./device.ts";
import { disableSubgroupMatrix, gemmCapabilities, type GemmCapabilities } from "./gemm-caps.ts";
import {
  skinnyGemmWGSL,
  subgroupMatrixGemmWGSL,
  tiledGemmWGSL,
  type GemmDType,
  type SkinnyGemmConfig,
  type SubgroupMatrixGemmConfig,
  type SubgroupMatrixSyntax,
  type TiledGemmConfig,
} from "./gemm-kernels.ts";
import {
  allocateGPUResidentBuffer,
  allocateOutputBuffer,
  bindingOf,
  dispatchKernel,
  getOrCreateComputePipeline,
  readBackBytes,
  releaseBuffer,
  uploadStorageBuffer,
  type SizedBuffer,
} from "./gpu-runtime.ts";

export type GemmKernel = "tiled" | "skinny" | "subgroup-matrix";

export interface GemmOptions {
  /** `b` is `[n, k]` (a Linear weight; computes `a · bᵀ`) instead of `[k, n]`. Default false. */
  transB?: boolean;
  /**
   * Force a kernel instead of the automatic choice (tests/benchmarks).
   * Throws if the forced kernel's preconditions don't hold for this
   * shape/device. Default `"auto"`.
   */
  kernel?: GemmKernel | "auto";
}

/**
 * Tile configurations, tuned on an Apple M2 (10-core GPU) via Dawn/Metal in
 * laya-js (bench/gemm.ts, bench/gemm-m.ts there) and untested for tuning on
 * discrete or mobile GPUs — correct everywhere, fastest where measured.
 */
export const GEMM_CONFIG: {
  readonly tiled: TiledGemmConfig;
  readonly skinny: readonly (SkinnyGemmConfig & { maxM: number })[];
  readonly subgroupMatrix: SubgroupMatrixGemmConfig & { minM: number };
} = Object.freeze({
  tiled: { BM: 64, BN: 64, BK: 16, TM: 4, TN: 4 },
  skinny: [
    { maxM: 40, WX: 16, TN: 4, WY: 4, KS: 4 },
    { maxM: 64, WX: 8, TN: 4, WY: 8, KS: 4 },
  ],
  // 2 subgroups, each a 32x32 block (4x4 fragments of 8x8).
  subgroupMatrix: { minM: 64, BM: 32, BN: 64, BK: 8, WM: 1, WN: 2 },
});

export interface GemmPlan {
  kernel: GemmKernel;
  /** WGSL source (also the pipeline-cache key). */
  code: string;
  /** Workgroup counts `[x, y]`. */
  groups: [number, number];
}

function skinnyConfigFor(m: number): (SkinnyGemmConfig & { maxM: number }) | undefined {
  return GEMM_CONFIG.skinny.find((c) => m <= c.maxM);
}

/** Preconditions of each kernel for a given problem (pure; exported for tests). */
export function gemmKernelApplicable(
  kernel: GemmKernel,
  m: number,
  k: number,
  n: number,
  transB: boolean,
  caps: GemmCapabilities,
): boolean {
  switch (kernel) {
    case "tiled":
      return true;
    case "skinny":
      return transB && k % 4 === 0 && skinnyConfigFor(m) !== undefined;
    case "subgroup-matrix":
      return caps.subgroupMatrix && k % 4 === 0 && (transB || n % 4 === 0);
  }
}

/** The automatic kernel choice (pure; exported for tests and so callers can see what `"auto"` will do). */
export function selectGemmKernel(m: number, k: number, n: number, transB: boolean, caps: GemmCapabilities): GemmKernel {
  if (gemmKernelApplicable("skinny", m, k, n, transB, caps)) return "skinny";
  if (m > GEMM_CONFIG.subgroupMatrix.minM && gemmKernelApplicable("subgroup-matrix", m, k, n, transB, caps)) {
    return "subgroup-matrix";
  }
  return "tiled";
}

/** Build the shader + dispatch grid for one problem (pure; exported for tests). */
export function planGemm(
  kernel: GemmKernel,
  dtype: GemmDType,
  m: number,
  k: number,
  n: number,
  transB: boolean,
  sgSyntax: SubgroupMatrixSyntax = "template",
): GemmPlan {
  if (kernel === "skinny") {
    const cfg = skinnyConfigFor(m);
    if (!cfg) throw new RangeError(`planGemm: skinny kernel needs m <= ${GEMM_CONFIG.skinny.at(-1)?.maxM}, got ${m}`);
    const TM = Math.max(1, Math.ceil(m / cfg.WY));
    return { kernel, code: skinnyGemmWGSL(dtype, cfg, TM), groups: [Math.ceil(n / (cfg.WX * cfg.TN)), 1] };
  }
  if (kernel === "subgroup-matrix") {
    const cfg = GEMM_CONFIG.subgroupMatrix;
    return {
      kernel,
      code: subgroupMatrixGemmWGSL(dtype, transB, cfg, sgSyntax),
      groups: [Math.ceil(n / cfg.BN), Math.ceil(m / cfg.BM)],
    };
  }
  const cfg = GEMM_CONFIG.tiled;
  const vecA = k % 4 === 0;
  const vecB = transB ? k % 4 === 0 : n % 4 === 0;
  return { kernel, code: tiledGemmWGSL(dtype, transB, vecA, vecB, cfg), groups: [Math.ceil(n / cfg.BN), Math.ceil(m / cfg.BM)] };
}

// ---- first-compile validation ---------------------------------------------

/**
 * Sources already compiled cleanly on each device. The first time a given
 * WGSL source is used on a device, pipeline creation is wrapped in a
 * validation error scope and awaited: WebGPU reports shader errors
 * asynchronously, so without this a bad shader would silently "succeed"
 * and leave the output buffer untouched (stale pooled data). This matters
 * mostly for the experimental subgroup-matrix extension, whose builtin
 * syntax has changed across Dawn/Chromium versions (see
 * `SubgroupMatrixSyntax`): on failure it retries the older syntax, then
 * disables that kernel for the device and falls back to `tiled`.
 */
const compileResults = new WeakMap<GPUDevice, Map<string, string | null>>();
const sgSyntaxFor = new WeakMap<GPUDevice, SubgroupMatrixSyntax>();

/** Compile (or fetch the cached pipeline for) `code`, returning the validation error message if it failed — remembered per device, since the pipeline cache would otherwise hand back the broken pipeline silently next time. */
async function compileChecked(device: GPUDevice, code: string): Promise<string | undefined> {
  let results = compileResults.get(device);
  if (!results) {
    results = new Map();
    compileResults.set(device, results);
  }
  const known = results.get(code);
  if (known !== undefined) return known ?? undefined;
  device.pushErrorScope("validation");
  getOrCreateComputePipeline(device, code);
  const err = await device.popErrorScope();
  results.set(code, err ? err.message : null);
  return err ? err.message : undefined;
}

async function resolvePlan(
  device: GPUDevice,
  dtype: GemmDType,
  m: number,
  k: number,
  n: number,
  opts: GemmOptions,
): Promise<GemmPlan> {
  const transB = opts.transB ?? false;
  if (dtype === "f16" && !device.features.has("shader-f16")) {
    throw new TypeError("GEMM: f16 needs a device with the shader-f16 feature (request it, e.g. via detectWebGPU())");
  }
  const caps = gemmCapabilities(device);
  const forced = opts.kernel && opts.kernel !== "auto" ? opts.kernel : undefined;
  if (forced && !gemmKernelApplicable(forced, m, k, n, transB, caps)) {
    throw new RangeError(`GEMM: kernel "${forced}" is not applicable to m=${m} k=${k} n=${n} transB=${transB} on this device`);
  }
  const kernel = forced ?? selectGemmKernel(m, k, n, transB, caps);
  if (kernel !== "subgroup-matrix") {
    const plan = planGemm(kernel, dtype, m, k, n, transB);
    const err = await compileChecked(device, plan.code);
    if (err) throw new Error(`GEMM: ${kernel} shader failed validation: ${err}`);
    return plan;
  }
  const syntaxes: SubgroupMatrixSyntax[] = [sgSyntaxFor.get(device) ?? "template"];
  if (syntaxes[0] === "template") syntaxes.push("bool");
  const errors: string[] = [];
  for (const syntax of syntaxes) {
    const plan = planGemm(kernel, dtype, m, k, n, transB, syntax);
    const err = await compileChecked(device, plan.code);
    if (!err) {
      sgSyntaxFor.set(device, syntax);
      return plan;
    }
    errors.push(`${syntax}: ${err}`);
  }
  if (forced) throw new Error(`GEMM: subgroup-matrix shader failed validation (${errors.join("; ")})`);
  disableSubgroupMatrix(device);
  return resolvePlan(device, dtype, m, k, n, opts);
}

// ---- dispatch ---------------------------------------------------------------

function encodeGemm(device: GPUDevice, plan: GemmPlan, a: SizedBuffer, b: SizedBuffer, out: SizedBuffer, m: number, k: number, n: number): void {
  dispatchKernel(device, plan.code, [a, b, out], [plan.groups[0], plan.groups[1]], {
    uniform: new Uint32Array([m, n, k, 0]),
    label: `gemm:${plan.kernel}`,
  });
}

function checkLengths(fn: string, aLen: number, bLen: number, m: number, k: number, n: number): void {
  if (aLen !== m * k) throw new RangeError(`${fn}: a.length ${aLen} !== m*k ${m * k}`);
  if (bLen !== k * n) throw new RangeError(`${fn}: b.length ${bLen} !== k*n ${k * n}`);
}

async function runGemmHost(
  fn: string,
  device: GPUDevice,
  dtype: GemmDType,
  a: Float32Array | Uint16Array,
  b: Float32Array | Uint16Array,
  m: number,
  k: number,
  n: number,
  opts: GemmOptions,
): Promise<ArrayBuffer> {
  checkLengths(fn, a.length, b.length, m, k, n);
  const bytesPer = dtype === "f16" ? 2 : 4;
  if (m * n === 0) return new ArrayBuffer(0);
  const plan = await resolvePlan(device, dtype, m, k, n, opts);
  const bufA = uploadStorageBuffer(device, a);
  const bufB = uploadStorageBuffer(device, b);
  const bufOut = allocateOutputBuffer(device, m * n, bytesPer);
  try {
    encodeGemm(device, plan, bufA, bufB, bufOut, m, k, n);
    return (await readBackBytes(device, bufOut.buffer, bufOut.byteLength)).slice(0, m * n * bytesPer);
  } finally {
    releaseBuffer(device, bufA);
    releaseBuffer(device, bufB);
    releaseBuffer(device, bufOut);
  }
}

/**
 * `a` is `m x k`, `b` is `k x n` (or `n x k` with `transB`), both row-major
 * contiguous `Float32Array`s; returns `m x n` row-major. Upload, dispatch
 * and readback happen per call — use {@link runGemm} with `GPUTensor`s to
 * keep operands and results on the GPU.
 */
export async function runGemmWGSL(
  device: GPUDevice,
  a: Float32Array,
  b: Float32Array,
  m: number,
  k: number,
  n: number,
  opts: GemmOptions = {},
): Promise<Float32Array> {
  return new Float32Array(await runGemmHost("runGemmWGSL", device, "f32", a, b, m, k, n, opts));
}

/**
 * f16 counterpart of {@link runGemmWGSL}: operands and result are raw
 * IEEE-754 binary16 bits (`Uint16Array`, tensor-core's f16 storage; view a
 * `Float16Array`'s buffer to pass one). Products accumulate in f32; the
 * result is rounded to f16 once, on store. Needs `shader-f16`.
 */
export async function runGemmF16WGSL(
  device: GPUDevice,
  a: Uint16Array,
  b: Uint16Array,
  m: number,
  k: number,
  n: number,
  opts: GemmOptions = {},
): Promise<Uint16Array> {
  return new Uint16Array(await runGemmHost("runGemmF16WGSL", device, "f16", a, b, m, k, n, opts));
}

/**
 * GPU-resident GEMM: `a` is a 2-D `[m, k]` `GPUTensor`, `b` is `[k, n]`
 * (or `[n, k]` with `transB`), same dtype (f32, or f16 with `shader-f16`).
 * Returns a new `[m, n]` `GPUTensor` of that dtype without any host copy —
 * chain it into further GPU ops, read it with `.toTensor()`, and `.free()`
 * it when done (inputs are never freed here).
 */
export async function runGemm(device: GPUDevice, a: GPUTensor, b: GPUTensor, opts: GemmOptions = {}): Promise<GPUTensor> {
  if (a.shape.length !== 2 || b.shape.length !== 2) {
    throw new RangeError(`runGemm: operands must be 2-D, got [${a.shape}] and [${b.shape}]`);
  }
  if (a.dtype !== b.dtype) throw new TypeError(`runGemm: dtype mismatch (${a.dtype} vs ${b.dtype})`);
  const transB = opts.transB ?? false;
  const [m, k] = a.shape as [number, number];
  const [bRows, bCols] = b.shape as [number, number];
  const kB = transB ? bCols : bRows;
  const n = transB ? bRows : bCols;
  if (kB !== k) {
    throw new RangeError(`runGemm: inner dimensions differ: a [${a.shape}] and b [${b.shape}]${transB ? " (transB)" : ""}`);
  }
  const dtype: GemmDType = a.dtype;
  const plan = m * n > 0 ? await resolvePlan(device, dtype, m, k, n, opts) : undefined;
  const out = allocateGPUResidentBuffer(device, m * n, dtype === "f16" ? 2 : 4);
  if (plan) encodeGemm(device, plan, bindingOf(a), bindingOf(b), out, m, k, n);
  return GPUTensor.fromBuffer(device, out.buffer, [m, n], dtype);
}
